[Settings]
# By default journals are loaded from your user folder
# To override this change JournalFolder below, e.g.:
# JournalFolder = '\\SOMENETWORKSHARE\Users\me\Saved Games\Frontier Developments\Elite Dangerous'
JournalFolder = ''
# UseUTC = false (default) uses local timezone, set true for UTC (in-game time)
UseUTC = false
# WarnKillRate sends a warning if kills/hour drop below set amount (Default: 20, log level 'KillRate')
WarnKillRate = 20
# WarnNoKills is time in minutes since last kill before sending a warning (Default: 20, log level 'NoKills')
WarnNoKills = 20
# BountyFaction shows faction name on each kill (Default: false)
BountyFaction = false
# BountyValue shows credits earned on each kill (Default: false)
BountyValue = false
# ExtendedStats shows extra stats e.g. recent kill rate (Default: false)
ExtendedStats = false
# DynamicTitle uses the window title to display some info (Default: true, only works on Windows OS)
DynamicTitle = true
# Show commander name in announcements
ShowCMDR = false


[Discord]
# Use the settings below to enable Discord webhook integration
# Webhook URL is located in Discord > Edit Channel > Integrations > Webhooks, e.g:
# WebhookURL = 'https://justanexample.fake/api/webhooks/lotsofnumbers/lotsoflettersnumbersandsymbols'
WebhookURL = ''
# User ID can be found by sending \@yourdiscordusername on Discord (use only the numbers), e.g.:
# UserID = 745279460191739562
UserID = 0
# ForumChannel specifies webhook is for a forum channel and enables thread support (Default: false)
ForumChannel = false
# ThreadCmdrNames = true include the commander name in the thread name along with the start time (Default: false)
ThreadCmdrNames = false
# Timestamp = true (default) appends a timestamp to Discord messages, set false to disable
Timestamp = true
# Identity = true (default) provides default name and avatar for webhook, set false to use user-set
Identity = true

[LogLevels]
# 0 = None
# 1 = Terminal
# 2 = Terminal & Discord
# 3 = Terminal & Discord with user ping
ScanEasy = 1            # Scans of 'easy' ships (Sidewinder etc.)
ScanHard = 2            # Scans of 'hard' ships (Python etc.)
KillEasy = 2            # Kills (bounty or bond) of easy ships
KillHard = 2            # Kills (bounty or bond) of hard ships
FighterHull = 2         # Fighter hull damage (20% increments)
FighterDown = 3         # Fighter destroyed
ShipShields = 3         # Ship shield failure
ShipHull = 3            # Ship hull damage (20% increments)
Died = 3                # Ship destruction
CargoLost = 3           # Cargo stolen
BaitValueLow = 2        # Insufficient cargo value messages
SecurityScan = 2        # Police ships being scanned
SecurityAttack = 3      # Police ships warning they are attacking you
FuelReport = 1          # Fuel use and time remaining
FuelLow = 2             # Fuel level low (under 20%)
FuelCritical = 3        # Fuel level critical (under 10%)
Missions = 2            # Kills completed for a mission
MissionsAll = 3         # Kills completed for all missions
SummaryKills = 2        # Summary of kills every 10 and at close
SummaryBounties = 2     # Summary of credits earned from bounties or bonds
Merits = 0              # Merits gained (powerplay-only)
SummaryMerits = 2       # Summary of merits (powerplay-only)
NoKills = 3             # Warning of no kills for configured time ('WarnNoKills' in Settings)
KillRate = 3            # Warning of low kill rate per hour ('WarnKillRate' in Settings)

# Custom profiles (advanced)
# You can set additional profiles to override settings as per the example below
# Profiles are loaded by passing -p <profilename> via command line or shortcut
#
# [MyAltProfile]
# Discord.WebhookURL = "https://discord.com/api/webhooks/myaltwebhook"
# LogLevels.ScanHard = 1
#
# Loading the above with {afk_monitor.py -p MyAltProfile} will override those two settings
# This feature is most useful for those with multiple accounts or PCs
# Note: profile, category and setting names are all case-sensitive
