[Settings]
# By default journals are loaded from your user folder
# To override this change JournalFolder below, e.g.:
# JournalFolder = '\\SOMENETWORKSHARE\Users\me\Saved Games\Frontier Developments\Elite Dangerous'
JournalFolder = ''
# UseUTC = false (default) uses local timezone, set true for UTC (in-game time)
UseUTC = false
# MissionTotal specifies the number of mission completions required to trigger log level 'MissionsAll'
MissionTotal = 20
# LowKillRate is a kills/hour threshold; if average drops below, log level 'Reports' is raised by 1 (Default: 20, 0 to disable)
LowKillRate = 20
# InactivityMax is time in minutes between journal updates before logging a warning (Default: 15, 0 to disable)
InactivityMax = 15

[Discord]
# Use the settings below to enable Discord webhook integration
# Webhook URL is located in Discord > Edit Channel > Integrations > Webhooks, e.g:
# WebhookURL = 'https://justanexample.fake/api/webhooks/lotsofnumbers/lotsoflettersnumbersandsymbols'
WebhookURL = ''
# User ID can be found by sending \@yourdiscordusername on Discord (use only the numbers), e.g.:
# UserID = 745279460191739562
UserID = 0
# Timestamp = true (default) appends a timestamp to Discord messages, set false to disable
Timestamp = true
# Identity = true (default) provides default name and avatar for webhook, set false to use user-set
Identity = true

[LogLevels]
# 0 = None
# 1 = Terminal
# 2 = Terminal & Discord
# 3 = Terminal & Discord with user ping
ScanEasy = 1
ScanHard = 2
KillEasy = 2
KillHard = 2
FighterHull = 2
FighterDown = 3
ShipShields = 3
ShipHull = 3
Died = 3
CargoLost = 3
BaitValueLow = 2
FuelLow = 2
FuelCritical = 3
Missions = 2
MissionsAll = 3
SummaryKills = 2
SummaryBounties = 1
Inactivity = 3

# Custom profiles (advanced)
# You can set additional profiles to override settings as per the example below
# Profiles are loaded by passing -p <profilename> via command line or shortcut
#
# [MyAltProfile]
# Discord.WebhookURL = "https://discord.com/api/webhooks/myaltwebhook"
# LogLevels.ScanHard = 1
#
# Loading the above with {afk_monitor.py -p MyAltProfile} will override those two settings
# This feature is most useful for those with multiple accounts or PCs